import { spawnSync } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { options } from './options.mjs';
const args = options({ format: { type: 'string', default: 'landscape' } });
if (!['landscape', 'portrait'].includes(args.format)) throw new Error('Invalid format');
const expected = JSON.parse(await readFile(join(args.out, `manifest-${args.format}.json`), 'utf8'));
const file = join(args.out, `frontier-${args.format}.mp4`);
const result = spawnSync('ffprobe', ['-v', 'error', '-count_frames', '-show_streams', '-show_format', '-of', 'json', file], { encoding: 'utf8' });
if (result.status !== 0) throw new Error(`ffprobe failed: ${result.stderr || result.error}`);
const probe = JSON.parse(result.stdout), video = probe.streams.find(s => s.codec_type === 'video');
assert.equal(video.codec_name, 'h264'); assert.equal(video.pix_fmt, 'yuv420p');
assert.equal(video.width, expected.width); assert.equal(video.height, expected.height);
assert.equal(Number(video.nb_read_frames), expected.frames);
assert(Math.abs(Number(probe.format.duration) - expected.duration) <= 1 / expected.fps);
assert.equal(probe.streams.length, 1, 'This film should contain only its video stream');
const actualHash = createHash('sha256').update(await readFile(args.data)).digest('hex');
assert.equal(expected.datasetSha256, actualHash, 'Film must match the current dataset');
const decoded = spawnSync('ffmpeg', ['-v', 'error', '-i', file, '-f', 'null', '-'], { encoding: 'utf8' });
assert.equal(decoded.status, 0, decoded.stderr);
console.log(`Verified ${file}: all ${expected.frames} frames decode; geometry, duration, codec and dataset hash match.`);
