import { spawnSync } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { options } from './options.mjs';
import { loudness } from './audio-master.mjs';
import { SCORE } from '../src/audio.mjs';
const args = options({ format: { type: 'string', default: 'landscape' } });
if (!['landscape', 'portrait'].includes(args.format)) throw new Error('Invalid format');
const expected = JSON.parse(await readFile(join(args.out, `manifest-${args.format}.json`), 'utf8'));
const file = join(args.out, `frontier-${args.format}.mp4`);
const result = spawnSync('ffprobe', ['-v', 'error', '-count_frames', '-show_streams', '-show_format', '-of', 'json', file], { encoding: 'utf8' });
if (result.status !== 0) throw new Error(`ffprobe failed: ${result.stderr || result.error}`);
const probe = JSON.parse(result.stdout), video = probe.streams.find(s => s.codec_type === 'video');
assert.equal(video.codec_name, 'h264'); assert.equal(video.pix_fmt, 'yuv420p');
assert.equal(video.width, expected.width); assert.equal(video.height, expected.height);
assert.equal(Number(video.nb_read_frames), expected.frames);
assert(Math.abs(Number(probe.format.duration) - expected.duration) <= 1 / expected.fps);
assert.equal(probe.streams.length, 2, 'Film must contain video and original soundtrack');
const audio = probe.streams.find(s => s.codec_type === 'audio');
assert.equal(audio.codec_name, 'aac'); assert.equal(audio.channels, 2); assert.equal(Number(audio.sample_rate), 48000);
assert(Math.abs(Number(audio.duration) - expected.duration) <= .05, 'Audio must cover the complete film');
const level = loudness(file);
assert(Math.abs(Number(level.input_i) - SCORE.targetLufs) <= 1.5, `Integrated loudness out of range: ${level.input_i}`);
assert(Number(level.input_tp) <= -1, `Encoded audio exceeds true-peak ceiling: ${level.input_tp}`);
assert(Number(level.input_lra) <= 9, `Excessive loudness range: ${level.input_lra}`);
const actualHash = createHash('sha256').update(await readFile(args.data)).digest('hex');
assert.equal(expected.datasetSha256, actualHash, 'Film must match the current dataset');
const decoded = spawnSync('ffmpeg', ['-v', 'error', '-xerror', '-i', file, '-f', 'null', '-'], { encoding: 'utf8' });
assert.equal(decoded.status, 0, decoded.stderr);
console.log(`Verified ${file}: all ${expected.frames} frames decode; geometry, duration, codecs and dataset hash match. Audio ${level.input_i} LUFS / ${level.input_tp} dBTP.`);
